"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabaseClient";

type SupabaseInsight = {
  status: string;
  detail: string;
  records?: number;
};

export default function Home() {
  const [insight, setInsight] = useState<SupabaseInsight>({
    status: "Connecting to Supabase...",
    detail: "This page will report the status of the configured database.",
  });

  useEffect(() => {
    let isMounted = true;
    const loadPreview = async () => {
      try {
        const { data, error } = await supabase
          .from("pwa_projects")
          .select("id, name")
          .limit(3);

        if (!isMounted) return;

        if (error) {
          setInsight({
            status: "Supabase ready",
            detail: error.message || "Table not configured yet.",
          });
          return;
        }

        setInsight({
          status: "Live data loaded",
          detail: `Retrieved ${data?.length ?? 0} rows from pwa_projects.`,
          records: data?.length,
        });
      } catch (error) {
        if (!isMounted) return;
        setInsight({
          status: "Connection issue",
          detail: error instanceof Error ? error.message : "Unknown error",
        });
      }
    };

    loadPreview();
    return () => {
      isMounted = false;
    };
  }, []);

  return (
    <div className="flex min-h-screen flex-col gap-6 bg-slate-950 px-6 pb-16 pt-10 text-slate-50 sm:px-16">
      <header className="mx-auto flex w-full max-w-5xl flex-col gap-4 rounded-3xl border border-slate-800 bg-slate-900/60 px-8 py-8 shadow-lg shadow-slate-900/80 backdrop-blur">
        <p className="text-sm uppercase tracking-[0.3em] text-sky-400">
          Capston + Supabase + PWA
        </p>
        <h1 className="text-4xl font-semibold leading-tight text-white sm:text-5xl">
          Instant Next.js starter with Vercel-ready PWA shell
        </h1>
        <p className="text-lg text-slate-300">
          This template wires Next.js App Router, Supabase, and offline support
          through <span className="text-sky-300">next-pwa</span>. Deploy the
          same setup straight to Vercel and connect your Supabase project.
        </p>
      </header>

      <section className="mx-auto grid w-full max-w-5xl gap-6 md:grid-cols-[1.2fr_0.8fr]">
        <article className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 shadow-lg shadow-slate-900/80">
          <div className="flex items-baseline justify-between gap-3">
            <h2 className="text-2xl font-semibold">Supabase insights</h2>
            {insight.records !== undefined && (
              <span className="rounded-full bg-slate-800 px-3 py-1 text-xs uppercase tracking-wider text-slate-200">
                {insight.records} records
              </span>
            )}
          </div>
          <p className="mt-3 text-sm text-slate-400">{insight.status}</p>
          <p className="mt-2 text-base text-slate-200">{insight.detail}</p>
          <div className="mt-6 flex flex-wrap gap-3">
            <Link
              className="inline-flex items-center justify-center rounded-full border border-slate-600 px-4 py-2 text-sm font-medium text-slate-100 transition hover:border-slate-400"
              href="https://supabase.com"
              target="_blank"
              rel="noreferrer"
            >
              Open Supabase project
            </Link>
            <Link
              className="inline-flex items-center justify-center rounded-full bg-sky-500 px-4 py-2 text-sm font-medium text-slate-950 transition hover:bg-sky-400"
              href="/"
            >
              Refresh data
            </Link>
          </div>
        </article>

        <article className="rounded-2xl border border-slate-800 bg-linear-to-br from-slate-900/60 to-slate-900/20 p-6 shadow-lg shadow-slate-900/80">
          <h3 className="text-lg font-semibold">PWA readiness</h3>
          <p className="mt-3 text-sm text-slate-300">
            The site caches pages, assets, and API responses generated by
            Supabase using <strong>next-pwa</strong>. When you install it from a
            supported browser, the shell continues to work offline while the
            latest Supabase state syncs once connectivity returns.
          </p>
          <ul className="mt-4 space-y-3 text-sm text-slate-200">
            {[
              "Lightweight service worker + caching via next-pwa",
              "Manifest + icons describe the experience to browsers",
              "Ready for Vercel deployment with environment variables",
            ].map((item) => (
              <li key={item} className="flex items-start gap-3">
                <span className="mt-0.5 h-2 w-2 rounded-full bg-sky-400" />
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </article>
      </section>

      <footer className="mx-auto flex w-full max-w-5xl flex-wrap items-center justify-between gap-4 rounded-3xl border border-slate-800 bg-slate-900/60 px-6 py-6 text-sm text-slate-400">
        <p>
          Ready for deployment? Set `NEXT_PUBLIC_SUPABASE_URL` +
          `NEXT_PUBLIC_SUPABASE_ANON_KEY` in Vercel and supply the same env vars
          locally via `.env.local`.
        </p>
        <Link
          className="font-semibold text-sky-300"
          href="https://vercel.com/dashboard"
          target="_blank"
          rel="noreferrer"
        >
          Visit Vercel dashboard
        </Link>
      </footer>
    </div>
  );
}
